### PR TITLE
Fix packaging of source release tarball

### LINKED ISSUE #254: 4.3.2 release is NOT gz archive
it is just a tar file:

```
bash$ wget https://github.com/Yubico/yubioath-desktop/releases/download/yubioath-desktop-4.3.2/yubioath-desktop-4.3.2.tar.gz
bash$ file yubioath-desktop-4.3.2.tar.gz 
yubioath-desktop-4.3.2.tar.gz: POSIX tar archive (GNU)
```

### PR DESCRIPTION
**Pull request by emlun**
This fixes #254.

### CODE REVIEW

**Comment by dagheyman** [comment]
This script is only run manually right? What about dropping the whole thing and just use `git archive --format=tar.gz` ? I don't think we should bundle submodules anyway.

**Comment by emlun** [comment]
Yeah, if we drop bundling submodules we can do that. What do you think @dainnilsson?

**Comment by dainnilsson** [comment]
The source tarball should be usable to build the binary artifacts, yes? Since the dependencies in the vendor directory are specific git commits (as opposed to properly versioned packages that you can point to), I would argue that they belong in the source release tarball.

**Comment by dagheyman** [comment]
My opinion is that every released version (which would have a source package) should only depend on properly released and versioned packages. I think this would make things easier for 3rd party packagers as well.

**Comment by dagheyman** [comment]
> By vendoring source code we make it part of our source release (and thus include it).

Thats fair. Maybe we should move away from the vendoring as well though. But that's outside the scope of this PR, so I'll approve it.

**Pull request merged**
