### PR TITLE
OS X window close behavior

### PR DESCRIPTION
**Pull request by tycho**
Adding Command+W shortcut to close the application window without closing the application.

Unfortunately, clicking the close button on the top left corner of the window will still quit the application, though.

### CODE REVIEW

**Comment by dainnilsson** [comment]
@dagheyman You're a mac user, any thoughts on this one?

**Comment by tycho** [comment]
@dagheyman See also related issue #101

**Comment by tycho** [comment]
Also this thing. https://github.com/Yubico/python-yubicommon/pull/8

**Comment by dagheyman** [comment]
Looks good to me, we should probably consider this for our other apps as well. Merged.

**Pull request merged**
