### PR TITLE
Partially addresses #187

### PR DESCRIPTION
**Pull request by artburkart**
**WIP:**
This PR doesn't address the whole issue, but it does add the up/down
navigation when the cursor is in the search bar. I don't know anything
about qml, so this is probably not clean by any means, but I'm happy to
change it. Maybe I'll learn more about how to write this stuff the
proper way as I continue to chip away at the requests outlined in #187.

### CODE REVIEW

**Comment by artburkart** [comment]
Is the flake8 failure legitimate? I haven't touched any of those files.

**Comment by emlun** [comment]
Thanks for contributing! I'll take a look soon, hopefully. Don't worry about the flake8 failures, that looks like existing lint that's been exposed by a recent upstream configuration change.

**Comment by artburkart** [comment]
@emlun - Thanks for following up, please don't spend too much time on this. I don't know qt or qml, so I have definitely done it wrong. The functionality I'm pondering is whether it would be useful to just search for creds when any letters are typed. I constantly want that while using this tool.

**Comment by emlun** [comment]
Thanks for contributing! Unfortunately you were right in this not being very clean. :) I started out from your solution but ended up with something completely different in the end: c8ab5b7b58bb319f00763f1be9533684641f35ed . Still, you're more than welcome to contribute more PRs if you feel like it!

**Comment by artburkart** [comment]
@emlun, thanks! I figured it would be a learning opportunity for me more than anything. A bit selfish on my end 😛

**Pull request closed without merging**
