### PR TITLE
Allow all three text fields in Add Credential dialog to submit the form

### PR DESCRIPTION
**Pull request by emlun**

### CODE REVIEW

**Comment by dagheyman** [comment]
Can we split this up? I'm fine with the submit on enter-feature, but have some issues with the inline error message (hardcoded color, new UI element introduced, layout issues).

**Comment by emlun** [comment]
Sure. I was thinking the latter was kind of necessary for the former to make any sense, but I guess without it it will just echo the button's behaviour.

**Comment by emlun** [comment]
Replaced by #295.

@dagheyman Do you feel like there's anything to be salvaged from the inline error message thing, or do we just drop it?

**Comment by dagheyman** [comment]
I suggest we drop it for now.

**Comment by emlun** [comment]
:+1:

**Pull request closed without merging**
