### PR TITLE
Fix QR code scanning on multi-monitor setups

### LINKED ISSUE #235: Scan QR Code does not work on Gnome
- Yubico Authenticator version:  4.3.2
- Operating system and version: Ubuntu 16.04
- YubiKey model and version:  Yubikey 4.3.7
- Bug description summary: QR code scan does not work

Steps to reproduce
---

Install gnome on ubuntu 16.04. Or on Arch Linux. Install the authenticator App

Both XOrg and Wayland doesn't scan QR codes from screen

Expected result
---

I scan scan QR codes from the screen

Actual results
---

QR Code was not found

### PR DESCRIPTION
**Pull request by emlun**
This fixes #235.

### CODE REVIEW

**Comment by dagheyman** [comment]
Code looks fine, let's just do some manual regression testing to be sure we don't brake anything.

- [ ] Windows (single monitor)
- [ ] Windows (dual monitor)
- [ ] macOS (single monitor)
- [ ] macOS (dual monitor)
- [ ] Ubuntu (single monitor)
- [ ] Ubuntu (dual monitor)

**Comment by dagheyman** [comment]
This seems to break the QR scan on macOS, on both dual and single monitor setup.

**Comment by emlun** [comment]
Ugh. Break how? Doesn't work at all, or only works on some regions of the screen?

**Comment by dagheyman** [comment]
With dual monitors it seems to fail with 
```
File "qrc:///py/qr/qrdecode.py", line 265, in remove_locator_patterns
    raise ValueError('Top-left square missing')
ValueError: Top-left square missing
```

when I removed my monitor I got: 

`qt.qpa.cocoa.window: Window position outside any known screen, using primary screen`

**Comment by emlun** [comment]
Hm, I don't see the same behaviour on Mac 10.12 with a single monitor. Does it work better with 10f255e?

**Comment by emlun** [comment]
Accidentally merged this into the `fix-indentation` branch instead of master; fixed and merged to master now.

**Pull request merged**
