### PR TITLE
Drop pyotherside as submodule

### PR DESCRIPTION
**Pull request by dagheyman**
Let build systems build it from source packages.

### CODE REVIEW

**Comment by emlun** [comment]
Maybe we should place the downloaded and compiled dependencies in a subdirectory like `lib/` or `build/lib/`?

We'll also need to update `dev-util/build-mac.sh` and `vagrant/windows/build.bat` to use this for local builds.

**Comment by dagheyman** [comment]
Updated to use a lib folder.

> We'll also need to update dev-util/build-mac.sh and vagrant/windows/build.bat to use this for local builds.

It doesn't look like any of those scripts actually builds and installs pyotherside, thats why I didn't update them.

**Comment by dagheyman** [comment]
(this is merged, not sure why github didn't recognise it)

**Comment by emlun** [comment]
Looks like you did a `git pull --rebase && git push` or something - the `drop-pyotherside-submodule` is unmerged on the GitHub side.

**Comment by emlun** [comment]
But yes, the commits ccc75aa109191b1de8a1e3e8bc656f4b0a87b18f and b9845f5fe81cfae8df8dfb25ab56655f37e3b3cb are in master as 7d69cbc395d8789c7f0d59f3bf64ec53109f4228 and 4d36c59bbbb892810f2ae2a28d26e44567e9ac39, respectively.

**Pull request merged**
